# Generated by Django 5.0.2 on 2024-09-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_password",
            field=models.CharField(max_length=128),
        ),
    ]
